import io
import json
import os
from datetime import datetime, timezone

import boto3
import openpyxl
import yaml

CF_R2_ACCESS_KEY = os.getenv("CF_R2_ACCESS_KEY_ID")
CF_R2_SECRET_KEY = os.getenv("CF_R2_SECRET_ACCESS_KEY")
CF_R2_ENDPOINT_URL = os.getenv("CF_R2_ENDPOINT_URL")
BUCKET_NAME = os.getenv("CF_R2_BUCKET_NAME", "")

CLEAN_ENDPOINT = ""
if CF_R2_ENDPOINT_URL:
    CLEAN_ENDPOINT = CF_R2_ENDPOINT_URL.rstrip("/").removesuffix("/" + BUCKET_NAME)

# Categories where excel/ holds one file per manufacturer instead of one
# combined category file -- tracked as multiple "sheets" in monitor_stats.yml.
MULTI_FILE_CATEGORIES = {"cars_for_sale", "cars_for_rent"}
MAX_OBSERVED_DATES = 30

STATS_HEADER = (
    "# Auto-generated by Common_files/build_qs_monitor.py\n"
    "# Stored in Cloudflare R2 -- do not add to the repo.\n"
    "# Re-run the daily monitor workflow to refresh.\n\n"
)


def get_client():
    return boto3.client(
        "s3",
        endpoint_url=CLEAN_ENDPOINT,
        aws_access_key_id=CF_R2_ACCESS_KEY,
        aws_secret_access_key=CF_R2_SECRET_KEY,
        region_name="auto",
    )


def list_today_categories(client, dt: datetime) -> list:
    prefix = f"qatarsale/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/"
    paginator = client.get_paginator("list_objects_v2")
    categories = []
    for page in paginator.paginate(Bucket=BUCKET_NAME, Prefix=prefix, Delimiter="/"):
        for cp in page.get("CommonPrefixes", []):
            name = cp["Prefix"][len(prefix):].rstrip("/")
            if name:
                categories.append(name)
    return sorted(categories)


def read_json_key(client, key: str):
    try:
        obj = client.get_object(Bucket=BUCKET_NAME, Key=key)
        return json.loads(obj["Body"].read().decode("utf-8"))
    except client.exceptions.NoSuchKey:
        return None
    except Exception as e:
        print(f"  [WARN] could not read {key}: {e}")
        return None


def read_started_at(client, dt: datetime):
    key = f"qatarsale/monitor/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/_run_started_at.json"
    data = read_json_key(client, key)
    if not data:
        return None
    return datetime.fromisoformat(data["started_at"])


# ---------------------------------------------------------------------------
# monitor.json
# ---------------------------------------------------------------------------

def build_monitor_json(client, dt: datetime, categories: list) -> dict:
    cat_entries = []
    total_requests = 0
    total_failed = 0
    duration_sums_sec = 0.0

    for category in categories:
        base = f"qatarsale/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/{category}"

        summary = read_json_key(client, f"{base}/summary/summary.json")
        total_ads = summary.get("total_listings", 0) if summary else 0

        cat_entries.append({
            "name": category,
            "slug": category,
            "total_ads": total_ads,
        })

        metrics = read_json_key(client, f"{base}/summary/request_metrics.json")
        if metrics:
            total_requests += metrics.get("requests_total", 0)
            duration_sums_sec += metrics.get("duration_sec", 0) or 0

        failed = read_json_key(client, f"{base}/summary/failed.json")
        if failed:
            total_failed += failed.get("total_failed", 0)

    started_at = read_started_at(client, dt)
    duration_sec = round((dt - started_at).total_seconds(), 2) if started_at else round(duration_sums_sec, 2)

    error_rate_pct = round(total_failed / (total_requests + total_failed) * 100, 2) if (total_requests + total_failed) > 0 else 0
    requests_per_min = round(total_requests / (duration_sec / 60), 2) if duration_sec > 0 else total_requests

    return {
        "scraped_at": dt.isoformat(),
        "saved_to_s3_date": dt.strftime("%Y-%m-%d"),
        "total_categories": len(cat_entries),
        "total_ads": sum(c["total_ads"] for c in cat_entries),
        "categories": cat_entries,
        "request_metrics": {
            "requests_total": total_requests,
            "requests_failed": total_failed,
            "error_rate_pct": error_rate_pct,
            "requests_per_min": requests_per_min,
            "duration_sec": duration_sec,
        },
    }


# ---------------------------------------------------------------------------
# monitor_stats.yml
# ---------------------------------------------------------------------------

def load_existing_stats(client) -> dict:
    key = "qatarsale/monitor/monitor_stats.yml"
    try:
        resp = client.get_object(Bucket=BUCKET_NAME, Key=key)
        return yaml.safe_load(resp["Body"].read().decode("utf-8")) or {}
    except client.exceptions.NoSuchKey:
        return {}
    except Exception as e:
        print(f"Could not load existing stats: {e} -- starting fresh.")
        return {}


def save_stats(client, stats: dict) -> None:
    key = "qatarsale/monitor/monitor_stats.yml"
    body = (STATS_HEADER + yaml.dump(stats, allow_unicode=True, default_flow_style=False, sort_keys=True)).encode("utf-8")
    client.put_object(Bucket=BUCKET_NAME, Key=key, Body=body, ContentType="text/yaml")
    print(f"Saved -> r2://{BUCKET_NAME}/{key}")


def inspect_excel(raw: bytes) -> list:
    sheets = []
    wb = openpyxl.load_workbook(io.BytesIO(raw), read_only=True, data_only=True)
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows_iter = ws.iter_rows(values_only=True)
        header_row = next(rows_iter, None)
        headers = [str(c) for c in header_row if c is not None] if header_row else []
        row_count = sum(1 for _ in rows_iter)
        sheets.append({"name": sheet_name, "row_count": row_count, "columns": headers})
    wb.close()
    return sheets


def accumulate_single_file(stats, category, size_bytes, sheets, date_str):
    entry = stats.setdefault(category, {"file_size_kb": {"min": None, "max": None, "last": None}, "observed_dates": [], "sheets": {}})
    if date_str not in entry["observed_dates"]:
        entry["observed_dates"].append(date_str)
        entry["observed_dates"] = sorted(entry["observed_dates"])[-MAX_OBSERVED_DATES:]
    kb = round(size_bytes / 1024, 1)
    fs = entry["file_size_kb"]
    fs["last"] = kb
    fs["min"] = min(kb, fs["min"]) if fs["min"] is not None else kb
    fs["max"] = max(kb, fs["max"]) if fs["max"] is not None else kb
    for sheet in sheets:
        se = entry["sheets"].setdefault(sheet["name"], {"columns": [], "row_count": {"min": None, "max": None, "last": None}})
        rc = sheet["row_count"]
        se["row_count"]["last"] = rc
        se["row_count"]["min"] = min(rc, se["row_count"]["min"]) if se["row_count"]["min"] is not None else rc
        se["row_count"]["max"] = max(rc, se["row_count"]["max"]) if se["row_count"]["max"] is not None else rc
        se["columns"].extend(c for c in sheet["columns"] if c not in se["columns"])


def accumulate_multi_file(client, stats, category, excel_keys, date_str):
    entry = stats.setdefault(category, {"file_size_kb": {"min": None, "max": None, "last": None}, "observed_dates": [], "sheets": {}})
    if date_str not in entry["observed_dates"]:
        entry["observed_dates"].append(date_str)
        entry["observed_dates"] = sorted(entry["observed_dates"])[-MAX_OBSERVED_DATES:]

    total_size_bytes = 0
    for key in excel_keys:
        make_name = os.path.splitext(os.path.basename(key))[0]
        obj = client.get_object(Bucket=BUCKET_NAME, Key=key)
        raw = obj["Body"].read()
        total_size_bytes += len(raw)
        sheets = inspect_excel(raw)
        if not sheets:
            continue
        row_count = sum(s["row_count"] for s in sheets)
        columns = sheets[0]["columns"]
        se = entry["sheets"].setdefault(make_name, {"columns": [], "row_count": {"min": None, "max": None, "last": None}})
        se["row_count"]["last"] = row_count
        se["row_count"]["min"] = min(row_count, se["row_count"]["min"]) if se["row_count"]["min"] is not None else row_count
        se["row_count"]["max"] = max(row_count, se["row_count"]["max"]) if se["row_count"]["max"] is not None else row_count
        se["columns"].extend(c for c in columns if c not in se["columns"])

    kb = round(total_size_bytes / 1024, 1)
    fs = entry["file_size_kb"]
    fs["last"] = kb
    fs["min"] = min(kb, fs["min"]) if fs["min"] is not None else kb
    fs["max"] = max(kb, fs["max"]) if fs["max"] is not None else kb


def build_monitor_stats(client, dt: datetime, categories: list) -> dict:
    stats = load_existing_stats(client)
    date_str = dt.strftime("%Y-%m-%d")

    for category in categories:
        prefix = f"qatarsale/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/{category}/excel/"
        resp = client.list_objects_v2(Bucket=BUCKET_NAME, Prefix=prefix, Delimiter="/")
        excel_keys = sorted(o["Key"] for o in resp.get("Contents", []) if o["Key"].endswith(".xlsx"))
        if not excel_keys:
            print(f"  {category}: no excel files found -- skipping stats.")
            continue

        if category in MULTI_FILE_CATEGORIES:
            accumulate_multi_file(client, stats, category, excel_keys, date_str)
            print(f"  {category}: {len(excel_keys)} manufacturer file(s) tracked as sheets")
        else:
            obj = client.get_object(Bucket=BUCKET_NAME, Key=excel_keys[0])
            raw = obj["Body"].read()
            sheets = inspect_excel(raw)
            accumulate_single_file(stats, category, len(raw), sheets, date_str)
            print(f"  {category}: {len(sheets)} sheet(s), {len(raw) / 1024:.1f} KB")

    return stats


def run():
    client = get_client()
    dt = datetime.now(timezone.utc)

    categories = [c for c in list_today_categories(client, dt) if c != "monitor"]
    print(f"Categories found for {dt.strftime('%Y-%m-%d')}: {categories}")

    monitor = build_monitor_json(client, dt, categories)
    with open("monitor.json", "w", encoding="utf-8") as f:
        json.dump(monitor, f, ensure_ascii=False, indent=2)
    key = f"qatarsale/monitor/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/monitor.json"
    client.upload_file("monitor.json", BUCKET_NAME, key, ExtraArgs={'ContentType': 'application/json; charset=utf-8'})
    print(f"Uploaded: {key} ({monitor['total_categories']} cats, {monitor['total_ads']} ads, "
          f"{monitor['request_metrics']['requests_total']} req, {monitor['request_metrics']['requests_per_min']} req/min)")

    stats = build_monitor_stats(client, dt, categories)
    body = (STATS_HEADER + yaml.dump(stats, allow_unicode=True, default_flow_style=False, sort_keys=True)).encode("utf-8")
    stats_key = "qatarsale/monitor/monitor_stats.yml"
    client.put_object(Bucket=BUCKET_NAME, Key=stats_key, Body=body, ContentType="text/yaml")
    print(f"Uploaded: {stats_key}")


if __name__ == "__main__":
    run()