folder: qatarsale
site_id: qatarsale-QA
display_name: QatarSale Qatar
website: qatarsale.com/ar/home
country: Qatar
github_username: devops5796-netizen
repo: QS
run_place: github
uses_proxy: false
r2_prefix: qatarsale
scrapers: 60
schedule: daily
data_format: xlsx
workflows:
  - "Cars For Sale"
  - "Jobs"
  - "Users"
  - "Simple Categories"
  - "Sub Categories"
  - "Sub Sub Categories"
  - "Showrooms"