name: Showrooms

on:
  workflow_run:
    workflows: ["Sub Sub Categories"]
    types:
      - completed
  workflow_dispatch:

jobs:
  scrape_cars_for_sale:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/showrooms_single_category.yml
    with:
      category: cars_for_sale
    secrets: inherit

  scrape_cars_for_rent:
    needs: scrape_cars_for_sale
    if: always()
    uses: ./.github/workflows/showrooms_single_category.yml
    with:
      category: cars_for_rent
    secrets: inherit